CREATE DATABASE QL_TTHT
GO
USE QL_TTHT

CREATE TABLE MUCTHANHTOAN
(
			MaMTT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			TiLe FLOAT
)

CREATE TABLE PHANQUYEN
(
			MaQuyen INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			TenQuyen NVARCHAR(50),
			ChiTietQuyen NVARCHAR(50)
)

CREATE TABLE TAIKHOAN
(
			TK NCHAR(50) PRIMARY KEY NOT NULL,
			MK NCHAR(50),
			MaQuyen INT REFERENCES PHANQUYEN(MaQuyen)
)

CREATE TABLE GIAOVIEN
(
			MaGV INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			HoTen NVARCHAR(50),
			SDT	CHAR(10),
			NgaySinh DATE,
			DiaChi NVARCHAR(max),
			GioiTinh NCHAR(3),
			MaMTT INT REFERENCES MUCTHANHTOAN(MaMTT),
			TK NCHAR(50) REFERENCES TAIKHOAN(TK) 
)


CREATE TABLE MUCUUDAI
(
			MaMUD INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			MucUuDai FLOAT
)
CREATE TABLE HOCVIEN
(
			MaHV INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			HoTen NVARCHAR(50),
			SDT	CHAR(10),
			NgaySinh DATE,
			DiaChi NVARCHAR(max),
			GioiTinh NCHAR(3),
			MaMUD INT REFERENCES MUCUUDAI(MaMUD),
)

CREATE TABLE MONHOC
( 
			MaMH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			TenMH NVARCHAR(50) 
)

CREATE TABLE MUCHOCPHI
(
			MaMHP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			HP1Buoi FLOAT
)

CREATE TABLE LOPHOC
(
			MaLH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			TenLH NVARCHAR(50),
			MaMHP INT REFERENCES MUCHOCPHI(MaMHP),
			MaMH INT REFERENCES MONHOC(MaMH),
			MaGV INT REFERENCES GIAOVIEN(MaGV)
)

CREATE TABLE HOCVIEN_LOPHOC
(
	MaLH INT REFERENCES LOPHOC(MaLH),
	MaHV INT REFERENCES HOCVIEN(MaHV)
)
CREATE TABLE BUOIHOC
(
			MaBH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			ThoiGian DATE,
			MaLH INT REFERENCES LOPHOC(MaLH)
)

CREATE TABLE DIEMDANH
(
			MaBH INT REFERENCES BUOIHOC(MaBH),
			MaHV INT REFERENCES HOCVIEN(MaHV),
			PRIMARY KEY(MaBH, MaHV)
)

CREATE TABLE BIENLAITRALUONG
(
			MaBLTL INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			NgayTra DATE,
			Thang INT,
			Luong FLOAT,
			DaThanhToan INT,
			MaGV INT REFERENCES GIAOVIEN(MaGV)
)

CREATE TABLE BIENLAITHUHOCPHI
(
			MaBLTHP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			NgayThu DATE,
			Thang INT,
			HocPhi FLOAT,
			DaThanhToan INT,
			MaHV INT REFERENCES HOCVIEN(MaHV)
)




