CREATE DATABASE QL_TT_HT
GO

USE QL_TT_HT

CREATE TABLE MUCTHANHTOAN
(
			MaMTT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			TiLe FLOAT
)

CREATE TABLE GIAOVIEN
(
			MaGV INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			HoTen NVARCHAR(50),
			SDT	CHAR(10),
			NgaySinh DATE,
			DiaChi NVARCHAR(50),
			GioiTinh NCHAR(3),
			MaMTT INT REFERENCES MUCTHANHTOAN(MaMTT),
)

CREATE TABLE MUCHOCPHI
(
			MaMHP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			MucUuDai FLOAT
)

CREATE TABLE HOCVIEN
(
			MaHV INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			HoTen NVARCHAR(50),
			SDT	CHAR(10),
			NgaySinh DATE,
			DiaChi NVARCHAR(50),
			GioiTinh NCHAR(3),
			MaMHP INT REFERENCES MUCHOCPHI(MaMHP),
)

CREATE TABLE MONHOC
( 
			MaMH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			TenMH NVARCHAR(50) 
)

CREATE TABLE LOPHOC
(
			MaLH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			TenLH NVARCHAR(50),
			HP1Buoi INT,
			MaMH INT REFERENCES MONHOC(MaMH),
			MaGV INT REFERENCES GIAOVIEN(MaGV)
)

CREATE TABLE HOCVIEN_LOPHOC
(
	MaLH INT REFERENCES LOPHOC(MaLH),
	MaHV INT REFERENCES HOCVIEN(MaHV)
)
CREATE TABLE BUOIHOC
(
			MaBH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			ThoiGian DATE,
			MaLH INT REFERENCES LOPHOC(MaLH)
)

CREATE TABLE DIEMDANH
(
			MaBH INT REFERENCES BUOIHOC(MaBH),
			MaHV INT REFERENCES HOCVIEN(MaHV),
			PRIMARY KEY(MaBH, MaHV)
)

CREATE TABLE BIENLAITRALUONG
(
			
			MaBLTL INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			NgayThu DATE,
			Luong FLOAT,
			MaGV INT REFERENCES GIAOVIEN(MaGV)
)

CREATE TABLE BIENLAITHUHOCPHI
(
			MaBLTHP CHAR(10),
			NgayThu DATE,
			HocPhi FLOAT,
			MaHV INT REFERENCES HOCVIEN(MaHV)
)



